#!/bin/bash

# Focus Clock v1.0.0 - GitHub Release Helper Script
# This script provides commands to help you create the GitHub release

echo "═══════════════════════════════════════════════════════════════"
echo "  Focus Clock v1.0.0 - GitHub Release Helper"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Release information
VERSION="1.0.0"
TAG="v1.0.0"
APK_PATH="build/app/outputs/flutter-apk/FocusClock.apk"
APK_NAME="FocusClock.apk"

echo -e "${GREEN}✓ Release APK built successfully!${NC}"
echo ""
echo "APK Location: $APK_PATH"
echo "APK Size: $(du -h $APK_PATH | cut -f1)"
echo "MD5 Checksum: $(md5sum $APK_PATH | cut -d' ' -f1)"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 1: Verify Repository Status${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Checking git status..."
git status --short
echo ""

echo -e "${YELLOW}If you see uncommitted changes above, commit them with:${NC}"
echo "  git add ."
echo "  git commit -m \"Release v1.0.0: Add release documentation\""
echo "  git push origin main"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 2: Copy APK to Release Directory (Optional)${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "You can rename the APK for better clarity:"
echo "  cp $APK_PATH ./$APK_NAME"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 3: Create GitHub Release${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "OPTION A: Using GitHub CLI (gh command)"
echo "----------------------------------------"
echo "If you have GitHub CLI installed:"
echo ""
echo "  gh release create $TAG $APK_PATH \\"
echo "    --title \"Focus Clock v$VERSION - Initial Release\" \\"
echo "    --notes-file RELEASE_NOTES_v1.0.0.md \\"
echo "    --target main"
echo ""
echo "OPTION B: Using GitHub Web Interface"
echo "-------------------------------------"
echo "1. Go to: https://github.com/YOUR_USERNAME/focus_clock/releases/new"
echo "2. Fill in the form:"
echo "   - Tag: $TAG"
echo "   - Target: main"
echo "   - Title: Focus Clock v$VERSION - Initial Release"
echo "   - Description: Copy content from RELEASE_NOTES_v1.0.0.md"
echo "3. Drag and drop: $APK_PATH"
echo "4. Click 'Publish release'"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 4: Verify Release${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "After creating the release:"
echo "1. Go to: https://github.com/YOUR_USERNAME/focus_clock/releases"
echo "2. Verify v$VERSION appears"
echo "3. Download the APK to test"
echo "4. Install on a test device"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 5: Test Installation${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Install on Android device:"
echo "  adb install $APK_PATH"
echo ""
echo "Or manually:"
echo "1. Download APK from GitHub release"
echo "2. Enable 'Install from Unknown Sources'"
echo "3. Open APK file on device"
echo "4. Follow installation prompts"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 6: Monitor Analytics${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Check Firebase Analytics:"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Select your Focus Clock project"
echo "3. Navigate to Analytics → Dashboard"
echo "4. Monitor:"
echo "   - App opens"
echo "   - Feature usage (timer, stopwatch, alarms)"
echo "   - Clock face changes"
echo "   - User engagement"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  🎉 Your Focus Clock v$VERSION is ready for release!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Documentation files created:"
echo "  ✓ RELEASE_NOTES_v1.0.0.md    - Comprehensive release notes"
echo "  ✓ INSTALLATION.md            - User installation guide"
echo "  ✓ RELEASE_PACKAGE_v1.0.0.md  - Release checklist and info"
echo "  ✓ release-helper.sh          - This script"
echo ""
echo "Release assets ready:"
echo "  ✓ $APK_PATH (52 MB)"
echo ""
echo -e "${YELLOW}Next action: Create the GitHub release!${NC}"
echo ""
